[build]
  functions = "./functions"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/data/billboards"
  to = "/.netlify/functions/get-data?items=billboards"
  status = 200

[[redirects]]
  from = "/data/articles"
  to = "/.netlify/functions/get-data?items=articles"
  status = 200
